name: web_socket_counter_api
description: An example counter api built with Dart Frog using WebSockets.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  broadcaster:
    path: packages/broadcaster
  dart_frog: ^0.3.0
  dart_frog_web_socket: ^0.1.0-dev.1
  web_socket_client:
    path: packages/web_socket_client

dev_dependencies:
  bloc_test: ^9.1.0
  http: ^0.13.5
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
